# Log level options: "debug", "info", "warn", "error"
logLevel: "info"

# Crypto modules to use, can be local, tpm or ecc608
crypto: "local"

# Options for TPM
# Path to the TPM device, e.g. "/dev/tpm0". Must be provided if crypto is set to "tpm".
# tpmPath: "/dev/tpm0"

# Bridge options
startBridge: true
localPublish: true

# BridgeInTopic is the topic to subscribe to for messages to be relayed to the other broker.
bridgeInTopic: "ql_bridge/in"
# BridgeOutTopic is the topic to publish to for messages to be relayed to the other broker.
bridgeOutTopic: "ql_bridge/out"

