# Log level options: "debug", "info", "warn", "error"
logLevel: "info"

# Crypto modules defaults to "tpm" and falls back to "local" if not available
crypto: "tpm"

# Path to the TPM device, "/dev/tpm0" is the default, specify below if different
# tpmPath: "/dev/tpm0"

# Bridge options
startBridge: true
localPublish: true

# BridgeInTopic is the topic to subscribe to for messages to be relayed to the other broker.
bridgeInTopic: "ql_bridge/in"
# BridgeOutTopic is the topic to publish to for messages to be relayed to the other broker.
bridgeOutTopic: "ql_bridge/out"

